#!/bin/bash
# 1. cleanup gitlab-runner configure file
rm ${PWD}/config/config.toml

# 2. create new  GitLab Runner config to use docker and privileged mode	    
docker run --rm -i \
           -v ${PWD}/config:/etc/gitlab-runner \
	   gitlab/gitlab-runner register\
	   --non-interactive \
	   --executor shell  \
	   --url http://`hostname -i | cut -d" " -f1`/ci \
           --registration-token CPLKM4x6Cb_FHGv6FNJ9 \
           --description "execute by shell" 
# 3. start gitlab-runner 
gitlab-runner run -c ${PWD}/config/config.toml

# 4. commit file to gitlab
cp ../.gitlab-ci.yml.shell ../.gitlab-ci.yml
git add ../.gitlab-ci.yml && git commit -m "test gitlab shell" && git push

