#!/bin/bash

docker run --rm -t -i \
           -v ${PWD}/config:/etc/gitlab-runner \
           gitlab/gitlab-runner register -n \
           --url http://`hostname -i | cut -d" " -f1`/ci \
           --registration-token CPLKM4x6Cb_FHGv6FNJ9 \
           --executor docker \
	   --executor shell \
           --description "Docker runner test"

docker run -d \
           --restart=no \
           --name gitlab-runner \
           -v ${PWD}/config:/etc/gitlab-runner \
           gitlab/gitlab-runner 
