#!/bin/bash

docker run --rm -t -i \
           -v ${PWD}/config:/etc/gitlab-runner \
           gitlab/gitlab-runner register -n \
           --url http://`hostname -i | cut -d" " -f1`/ci \
           --registration-token CPLKM4x6Cb_FHGv6FNJ9 \
           --executor docker \
           --description "Docker runner in docker" \
	   --docker-image "docker:stable" \
          --docker-privileged

#gitlab-runner register -n \
#   --url http://`hostname -i | cut -d" " -f1`/ci \
#   --registration-token CPLKM4x6Cb_FHGv6FNJ9 \
#   --executor docker \
#   --description "Docker runner in docker" \
#   --docker-image "docker:stable" \
#   --docker-privileged

docker run -d \
	   --restart=no \
           --name gitlab-runner_docker \
           -v ${PWD}/config:/etc/gitlab-runner \
           gitlab/gitlab-runner 
