version: '3.4'
services:
  redis:
    image: 'redis:latest'
    #container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379-6390:6379'
    expose:
      - 6379    
    volumes:
      - $PWD/redis_data:/var/lib/redis:Z
  mariadb:
    image: 'mariadb:10.2'
    #container_name: mariadb
    labels:
      kompose.service.type: nodeport
    ports:
      - '3316-3326:3306'
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  mariadb_data:
    driver: local
    name: mariadb-data
    driver_opts:
      type: none
      device: $PWD/mariadb_data
      o: bind
 
