#!/bin/bash

docker run `# --rm` \
        -d \
        --restart=no \
        --name daikuei_registry \
        -v ${PWD}/storage:/var/lib/registry \
        -v ${PWD}/config/private_reg_config.yml:/etc/docker/registry/config.yml \
        -p 5000:5000 \
        registry:latest



