image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: 172.17.0.1:5000/my-image:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: 172.17.0.1:5000/my-image:latest

services:
  - docker:dind

stages:
  - build
  
before_script:
   - docker info
   - whoami 

build:
   stage: build
   script:
     - docker build -t $CONTAINER_TEST_IMAGE .
     - docker push $CONTAINER_TEST_IMAGE

